name: SeeCustomCrafts
version: '${project.version}'
main: ru.gdev.seecustomcrafts.SeeCustomCrafts
api-version: '1.16'
depend: [ProtocolLib]
authors: [GDev]
website: https://gdev.seemine.su
commands:
  seecustomcrafts:
    description: Управление кастомными крафтами
    usage: /seecustomcrafts <create|edit|remove|list|reload>
    aliases: [scc, customcrafts, seecc]
